// Author/Creator/Modifier: Neil Mitchell
using System;using System.IO;using System.Linq;using System.Reflection;using System.Security.Cryptography;using System.Collections.Generic;using LauSetup;
public class RangeTestTests {
 static void Check(bool v,string m){if(!v)throw new Exception(m);} static void Reject(Action a,string m){bool hit=false;try{a();}catch(IOException){hit=true;}Check(hit,m);}
 static string StreamHash(string resource){using(var s=Assembly.GetExecutingAssembly().GetManifestResourceStream(resource))using(var sha=SHA256.Create())return BitConverter.ToString(sha.ComputeHash(s)).Replace("-","").ToLowerInvariant();}
 static byte[] MinimalMpq(){const int count=8;uint[] table=new uint[count*4];for(int i=0;i<table.Length;i++)table[i]=0xFFFFFFFF;uint key=MpqScan.NameHash("(hash table)",3),seed=0xEEEEEEEE;uint[] crypt=new uint[1280];uint z=0x100001;for(int i=0;i<256;i++)for(int j=0;j<5;j++){z=(z*125+3)%0x2AAAAB;uint hi=(z&65535)<<16;z=(z*125+3)%0x2AAAAB;crypt[i+j*256]=hi|(z&65535);}using(var m=new MemoryStream())using(var w=new BinaryWriter(m)){w.Write(0x1A51504Du);w.Write(32u);w.Write((uint)(32+count*16));w.Write((ushort)0);w.Write((ushort)3);w.Write(32u);w.Write((uint)(32+count*16));w.Write((uint)count);w.Write(0u);unchecked{foreach(uint plain in table){seed+=crypt[1024+(key&255)];w.Write(plain^(key+seed));key=((~key<<21)+0x11111111)|(key>>11);seed=plain+seed+(seed<<5)+3;}}return m.ToArray();}}
 public static int Main(string[] a){try{
  if(a.Length<4)throw new ArgumentException("Usage: RangeTestTests <absolute-empty-output> <absolute-baseline-payload> <absolute-wow-3.3.5a-exe> <absolute-test-payload>");if(a.Take(4).Any(x=>!Path.IsPathRooted(x)))throw new ArgumentException("All fixture paths must be absolute.");string output=Path.GetFullPath(a[0]),baseline=Path.GetFullPath(a[1]),exe=Path.GetFullPath(a[2]),payload=Path.GetFullPath(a[3]);if(Directory.Exists(output)&&Directory.EnumerateFileSystemEntries(output).Any())throw new IOException("Fixture output must be empty; refusing to overwrite prior evidence.");if(!Directory.Exists(baseline)||!File.Exists(exe)||!Directory.Exists(payload))throw new IOException("Fixture inputs are missing.");var old=RangeTest.Baseline();var test=Catalog.Embedded();Directory.CreateDirectory(output);int passed=0;
  var editions=old.Assets.Keys.Where(k=>k.StartsWith("Y-")).OrderBy(k=>k).ToArray();Check(editions.Length==6,"Expected six supported Patch-Y editions.");var payloadHashes=new Dictionary<string,string>();foreach(var edition in editions){string file=Path.Combine(payload,edition+".mpq");Check(Hash.Matches(file,test.Get(edition).Sha256,test.Get(edition).Bytes),"Payload does not match the embedded range catalog: "+edition);payloadHashes.Add(edition,Hash.FileHash(file));}string baseDir=AppDomain.CurrentDomain.BaseDirectory,installer=Path.Combine(baseDir,"LauIccRangeTest.exe"),source=Path.GetFullPath(Path.Combine(baseDir,"..","app","RangeTest.cs"));Check(File.Exists(installer),"LauIccRangeTest.exe must be beside RangeTestTests.exe so results bind the tested installer.");
  foreach(var id in editions){string root=Path.Combine(output,id);string locale="enUS";Directory.CreateDirectory(Path.Combine(root,"Data",locale));File.Copy(exe,Path.Combine(root,"WoW.exe"),true);File.WriteAllBytes(Path.Combine(root,"Data","common.mpq"),MinimalMpq());File.WriteAllBytes(Path.Combine(root,"Data",locale,"locale-"+locale+".mpq"),MinimalMpq());if(!id.StartsWith("Y-Non-HD")){File.WriteAllBytes(Path.Combine(root,"Data","patch-f.mpq"),MinimalMpq());File.WriteAllBytes(Path.Combine(root,"Data",locale,"patch-"+locale+"-F.MPQ"),MinimalMpq());}
   var paths=new[]{Path.Combine(root,"Data","patch-y.mpq"),Path.Combine(root,"Data",locale,"patch-"+locale+"-Y.MPQ")};foreach(var p in paths)File.Copy(Path.Combine(baseline,id+".mpq"),p,true);string sentinel=Path.Combine(root,"Data","patch-unrelated.mpq");File.WriteAllBytes(sentinel,MinimalMpq());string sentinelHash=Hash.FileHash(sentinel);
   Check(RangeTest.Plan(root,old,test).Operations.Count==2,"Baseline was not upgraded: "+id);
   string other=editions.First(x=>x!=id);File.Copy(Path.Combine(baseline,other+".mpq"),paths[1],true);Reject(()=>RangeTest.Plan(root,old,test),"Mixed editions accepted: "+id);File.Copy(Path.Combine(baseline,id+".mpq"),paths[1],true);
   using(var s=new FileStream(paths[0],FileMode.Open,FileAccess.ReadWrite)){s.Position=s.Length-1;int b=s.ReadByte();s.Position--;s.WriteByte((byte)(b^1));}Reject(()=>RangeTest.Plan(root,old,test),"One-byte baseline drift accepted: "+id);File.Copy(Path.Combine(baseline,id+".mpq"),paths[0],true);
   foreach(var recovery in new[]{"INSTALLED","COMMITTING","RECOVERY_REQUIRED"}){File.Copy(Path.Combine(payload,id+".mpq"),paths[0],true);Check(RangeTest.Plan(root,old,test).Operations.Count==1,"Partial placement was not accepted: "+id);RangeTest.Apply(root,payload);if(recovery!="INSTALLED"){string journal=Transaction.Journals(root).First(p=>Transaction.Status(p)=="INSTALLED");var record=Json.Parse<Journal>(File.ReadAllText(journal));record.Status=recovery;Json.Save(journal,record);}RangeTest.Undo(root);Check(Hash.Matches(paths[0],test.Get(id).Sha256,test.Get(id).Bytes)&&Hash.Matches(paths[1],old.Get(id).Sha256,old.Get(id).Bytes),"One-placement "+recovery+" recovery did not restore its exact pre-operation state: "+id);File.Copy(Path.Combine(baseline,id+".mpq"),paths[0],true);}
   string invalid=Path.Combine(root,"invalid-payload");Directory.CreateDirectory(invalid);File.WriteAllText(Path.Combine(invalid,id+".mpq"),"corrupt");Reject(()=>RangeTest.Apply(root,invalid),"Corrupt payload accepted: "+id);foreach(var p in paths)Check(Hash.Matches(p,old.Get(id).Sha256,old.Get(id).Bytes),"Corrupt payload wrote client bytes: "+id);
   RangeTest.Apply(root,payload);Check(RangeTest.Apply(root,payload)==null,"Repeat was not a no-op: "+id);foreach(var p in paths)Check(Hash.Matches(p,test.Get(id).Sha256,test.Get(id).Bytes),"Installed test bytes mismatch: "+id);
   using(var s=new FileStream(paths[0],FileMode.Open,FileAccess.ReadWrite)){s.Position=s.Length-1;int b=s.ReadByte();s.Position--;s.WriteByte((byte)(b^1));}Reject(()=>RangeTest.Plan(root,old,test),"One-byte test drift accepted: "+id);File.Copy(Path.Combine(payload,id+".mpq"),paths[0],true);
   RangeTest.Undo(root);foreach(var p in paths)Check(Hash.Matches(p,old.Get(id).Sha256,old.Get(id).Bytes),"Exact rollback failed: "+id);Check(Hash.FileHash(sentinel)==sentinelHash,"Unrelated Patch-Y-adjacent sentinel changed: "+id);Reject(()=>RangeTest.Undo(root),"Restore selected a non-owned journal: "+id);
   string foreign=Path.Combine(root,"LauSetupBackups","transactions","foreign-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(foreign);Json.Save(Path.Combine(foreign,"install.json"),new Journal{Root=root,Locale=locale,Edition="foreign",Status="COMMITTING",Files=new System.Collections.Generic.List<JournalEntry>{new JournalEntry{Relative=@"Data\patch-q.mpq",Existed=true,OldHash=new string('0',64),OldBytes=1,NewHash=new string('1',64),NewBytes=1}}});Reject(()=>RangeTest.Undo(root),"Non-owned pending journal was accepted: "+id);Check(Hash.FileHash(sentinel)==sentinelHash,"Non-owned pending journal changed the sentinel: "+id);Console.WriteLine("PASS "+id);passed++;
  }
  Json.Save(Path.Combine(output,"validation.json"),new{Author="Neil Mitchell",Creator="Neil Mitchell",LastModifiedBy="Neil Mitchell",passed,six_editions=true,mixed_and_single_byte_rejected=true,corrupt_payload_before_write=true,partial_placement_installed_committing_and_recovery_required_rollback=true,repeat_no_op_and_exact_rollback=true,unrelated_sentinel_and_pending_journal_preserved=true,embeddedRangeCatalogSha256=StreamHash("LauSetup.Catalog.json"),embeddedBaselineCatalogSha256=StreamHash("LauSetup.Baseline.json"),payloadYHashes=payloadHashes,testRunnerSha256=Hash.FileHash(Assembly.GetExecutingAssembly().Location),rangeInstallerSha256=Hash.FileHash(installer),rangeTestSourceSha256=File.Exists(source)?Hash.FileHash(source):null});return 0;
 }catch(Exception e){Console.Error.WriteLine(e);return 1;}}
}
