using System.Reflection;
[assembly: AssemblyTitle("Lau BPC Floor Markers Test 2")]
[assembly: AssemblyDescription("Experimental Wrath 3.3.5a BPC floor-marker installer. Author, creator and modifier: Neil Mitchell.")]
[assembly: AssemblyCompany("Neil Mitchell")]
[assembly: AssemblyProduct("Lau Setup")]
[assembly: AssemblyCopyright("Neil Mitchell")]
[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyFileVersion("0.1.0.0")]
[assembly: AssemblyInformationalVersion("0.2.0-test2-bpc-floor-markers")]
[assembly: AssemblyMetadata("Author", "Neil Mitchell")]
[assembly: AssemblyMetadata("Creator", "Neil Mitchell")]
[assembly: AssemblyMetadata("LastModifiedBy", "Neil Mitchell")]
